### ISSUE TITLE
Filepath of downloaded object

### ISSUE THREAD

**Issue by SylvainCecchetto** [willforde/urlquick#3]
Hi Willforde,

Is there a way to get the final filepath on the of the downloaded webpage/image?

Some thing like:

```python
r = urlquick.get(url)
print "File location on disk: " + r.location
```

Thank you!

**Comment by willforde** [comment]
No. It's not really possible as I store the data encoded as base64 in a json file, along with all the header info.

**Comment by SylvainCecchetto** [comment]
Ok no problem ;-)
Thank you for the informations
