### ISSUE TITLE
resp.parse issue with html response

### ISSUE THREAD

**Issue by wwark** [willforde/urlquick#6]
Hi @willforde,

I tried to remove beautifullsoup from this code in attchement.
[cnews.zip](https://github.com/willforde/urlquick/files/2975021/cnews.zip)

It parsed this URL.
https://www.cnews.fr/service/dm_loadmore/dm_emission_index_emissions/1/0

The result of my code is 
![Screenshot from 2019-03-17 11-35-42](https://user-images.githubusercontent.com/469461/54489069-cfd41880-48a8-11e9-9db7-9ea288dff1b6.png)

Thanks for your help,
Wwark

**Comment by willforde** [comment]
That data is actually json data. This should fix the problem.
```
import urlquick
import htmlement

resp = urlquick.get("https://www.cnews.fr/service/dm_loadmore/dm_emission_index_emissions/1/0")
parser = htmlement.HTMLement()
parser.feed(resp.json())
data = parser.close()

print(data)
>>> <Element 'html' at 0x7fe18569e598>
```

**Comment by wwark** [comment]
Thanks it is working !!!!
